// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/base-org/pessimism/internal/api/service (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/base-org/pessimism/internal/api/models"
	core "github.com/base-org/pessimism/internal/core"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockService) CheckHealth() *models.HealthCheck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth")
	ret0, _ := ret[0].(*models.HealthCheck)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockServiceMockRecorder) CheckHealth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockService)(nil).CheckHealth))
}

// ProcessInvariantRequest mocks base method.
func (m *MockService) ProcessInvariantRequest(arg0 models.InvRequestBody) (core.InvSessionUUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessInvariantRequest", arg0)
	ret0, _ := ret[0].(core.InvSessionUUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessInvariantRequest indicates an expected call of ProcessInvariantRequest.
func (mr *MockServiceMockRecorder) ProcessInvariantRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessInvariantRequest", reflect.TypeOf((*MockService)(nil).ProcessInvariantRequest), arg0)
}
