// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/base-org/pessimism/internal/alert (interfaces: ClientMap)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	client "github.com/base-org/pessimism/internal/client"
	core "github.com/base-org/pessimism/internal/core"
	gomock "github.com/golang/mock/gomock"
)

// MockClientMap is a mock of ClientMap interface.
type MockClientMap struct {
	ctrl     *gomock.Controller
	recorder *MockClientMapMockRecorder
}

// MockClientMapMockRecorder is the mock recorder for MockClientMap.
type MockClientMapMockRecorder struct {
	mock *MockClientMap
}

// NewMockClientMap creates a new mock instance.
func NewMockClientMap(ctrl *gomock.Controller) *MockClientMap {
	mock := &MockClientMap{ctrl: ctrl}
	mock.recorder = &MockClientMapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientMap) EXPECT() *MockClientMapMockRecorder {
	return m.recorder
}

// GetPagerDutyClients mocks base method.
func (m *MockClientMap) GetPagerDutyClients(arg0 core.Severity) []client.PagerDutyClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPagerDutyClients", arg0)
	ret0, _ := ret[0].([]client.PagerDutyClient)
	return ret0
}

// GetPagerDutyClients indicates an expected call of GetPagerDutyClients.
func (mr *MockClientMapMockRecorder) GetPagerDutyClients(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPagerDutyClients", reflect.TypeOf((*MockClientMap)(nil).GetPagerDutyClients), arg0)
}

// GetSlackClients mocks base method.
func (m *MockClientMap) GetSlackClients(arg0 core.Severity) []client.SlackClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlackClients", arg0)
	ret0, _ := ret[0].([]client.SlackClient)
	return ret0
}

// GetSlackClients indicates an expected call of GetSlackClients.
func (mr *MockClientMapMockRecorder) GetSlackClients(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlackClients", reflect.TypeOf((*MockClientMap)(nil).GetSlackClients), arg0)
}

// InitAlertClients mocks base method.
func (m *MockClientMap) InitializeRouting(arg0 *core.AlertRoutingParams) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitializeRouting", arg0)
}

// InitAlertClients indicates an expected call of InitAlertClients.
func (mr *MockClientMapMockRecorder) InitAlertClients(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeRouting", reflect.TypeOf((*MockClientMap)(nil).InitializeRouting), arg0)
}

// SetPagerDutyClients mocks base method.
func (m *MockClientMap) SetPagerDutyClients(arg0 []client.PagerDutyClient, arg1 core.Severity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPagerDutyClients", arg0, arg1)
}

// SetPagerDutyClients indicates an expected call of SetPagerDutyClients.
func (mr *MockClientMapMockRecorder) SetPagerDutyClients(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPagerDutyClients", reflect.TypeOf((*MockClientMap)(nil).SetPagerDutyClients), arg0, arg1)
}

// SetSlackClients mocks base method.
func (m *MockClientMap) SetSlackClients(arg0 []client.SlackClient, arg1 core.Severity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSlackClients", arg0, arg1)
}

// SetSlackClients indicates an expected call of SetSlackClients.
func (mr *MockClientMapMockRecorder) SetSlackClients(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSlackClients", reflect.TypeOf((*MockClientMap)(nil).SetSlackClients), arg0, arg1)
}
