// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/base-org/pessimism/internal/engine (interfaces: Manager)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	core "github.com/base-org/pessimism/internal/core"
	heuristic "github.com/base-org/pessimism/internal/engine/heuristic"
	gomock "github.com/golang/mock/gomock"
)

// EngineManager is a mock of Manager interface.
type EngineManager struct {
	ctrl     *gomock.Controller
	recorder *EngineManagerMockRecorder
}

// EngineManagerMockRecorder is the mock recorder for EngineManager.
type EngineManagerMockRecorder struct {
	mock *EngineManager
}

// NewEngineManager creates a new mock instance.
func NewEngineManager(ctrl *gomock.Controller) *EngineManager {
	mock := &EngineManager{ctrl: ctrl}
	mock.recorder = &EngineManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *EngineManager) EXPECT() *EngineManagerMockRecorder {
	return m.recorder
}

// DeleteHeuristicSession mocks base method.
func (m *EngineManager) DeleteHeuristicSession(arg0 core.UUID) (core.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHeuristicSession", arg0)
	ret0, _ := ret[0].(core.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteHeuristicSession indicates an expected call of DeleteHeuristicSession.
func (mr *EngineManagerMockRecorder) DeleteHeuristicSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHeuristicSession", reflect.TypeOf((*EngineManager)(nil).DeleteHeuristicSession), arg0)
}

// DeployHeuristicSession mocks base method.
func (m *EngineManager) DeployHeuristicSession(arg0 *heuristic.DeployConfig) (core.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployHeuristicSession", arg0)
	ret0, _ := ret[0].(core.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeployHeuristicSession indicates an expected call of DeployHeuristicSession.
func (mr *EngineManagerMockRecorder) DeployHeuristicSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployHeuristicSession", reflect.TypeOf((*EngineManager)(nil).DeployHeuristicSession), arg0)
}

// EventLoop mocks base method.
func (m *EngineManager) EventLoop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventLoop")
	ret0, _ := ret[0].(error)
	return ret0
}

// EventLoop indicates an expected call of EventLoop.
func (mr *EngineManagerMockRecorder) EventLoop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventLoop", reflect.TypeOf((*EngineManager)(nil).EventLoop))
}

// GetInputType mocks base method.
func (m *EngineManager) GetInputType(arg0 core.HeuristicType) (core.TopicType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInputType", arg0)
	ret0, _ := ret[0].(core.TopicType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInputType indicates an expected call of GetInputType.
func (mr *EngineManagerMockRecorder) GetInputType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInputType", reflect.TypeOf((*EngineManager)(nil).GetInputType), arg0)
}

// Shutdown mocks base method.
func (m *EngineManager) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *EngineManagerMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*EngineManager)(nil).Shutdown))
}

// Transit mocks base method.
func (m *EngineManager) Transit() chan core.HeuristicInput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transit")
	ret0, _ := ret[0].(chan core.HeuristicInput)
	return ret0
}

// Transit indicates an expected call of Transit.
func (mr *EngineManagerMockRecorder) Transit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transit", reflect.TypeOf((*EngineManager)(nil).Transit))
}
