// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/base-org/pessimism/internal/client (interfaces: IxClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/ethereum-optimism/optimism/indexer/api/models"
	common "github.com/ethereum/go-ethereum/common"
	gomock "github.com/golang/mock/gomock"
)

// MockIxClient is a mock of IxClient interface.
type MockIxClient struct {
	ctrl     *gomock.Controller
	recorder *MockIxClientMockRecorder
}

// MockIxClientMockRecorder is the mock recorder for MockIxClient.
type MockIxClientMockRecorder struct {
	mock *MockIxClient
}

// NewMockIxClient creates a new mock instance.
func NewMockIxClient(ctrl *gomock.Controller) *MockIxClient {
	mock := &MockIxClient{ctrl: ctrl}
	mock.recorder = &MockIxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIxClient) EXPECT() *MockIxClientMockRecorder {
	return m.recorder
}

// GetAllWithdrawalsByAddress mocks base method.
func (m *MockIxClient) GetAllWithdrawalsByAddress(arg0 common.Address) ([]models.WithdrawalItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithdrawalsByAddress", arg0)
	ret0, _ := ret[0].([]models.WithdrawalItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithdrawalsByAddress indicates an expected call of GetAllWithdrawalsByAddress.
func (mr *MockIxClientMockRecorder) GetAllWithdrawalsByAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithdrawalsByAddress", reflect.TypeOf((*MockIxClient)(nil).GetAllWithdrawalsByAddress), arg0)
}
