// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/base-org/pessimism/internal/client (interfaces: IndexerClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/ethereum-optimism/optimism/indexer/api/models"
	common "github.com/ethereum/go-ethereum/common"
	gomock "github.com/golang/mock/gomock"
)

// MockIndexerClient is a mock of IndexerClient interface.
type MockIndexerClient struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerClientMockRecorder
}

// MockIndexerClientMockRecorder is the mock recorder for MockIndexerClient.
type MockIndexerClientMockRecorder struct {
	mock *MockIndexerClient
}

// NewMockIndexerClient creates a new mock instance.
func NewMockIndexerClient(ctrl *gomock.Controller) *MockIndexerClient {
	mock := &MockIndexerClient{ctrl: ctrl}
	mock.recorder = &MockIndexerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexerClient) EXPECT() *MockIndexerClientMockRecorder {
	return m.recorder
}

// GetAllWithdrawalsByAddress mocks base method.
func (m *MockIndexerClient) GetAllWithdrawalsByAddress(arg0 common.Address) ([]models.WithdrawalItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithdrawalsByAddress", arg0)
	ret0, _ := ret[0].([]models.WithdrawalItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithdrawalsByAddress indicates an expected call of GetAllWithdrawalsByAddress.
func (mr *MockIndexerClientMockRecorder) GetAllWithdrawalsByAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithdrawalsByAddress", reflect.TypeOf((*MockIndexerClient)(nil).GetAllWithdrawalsByAddress), arg0)
}
