// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/base-org/pessimism/internal/engine/invariant (interfaces: Invariant)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	core "github.com/base-org/pessimism/internal/core"
	gomock "github.com/golang/mock/gomock"
)

// MockInvariant is a mock of Invariant interface.
type MockInvariant struct {
	ctrl     *gomock.Controller
	recorder *MockInvariantMockRecorder
}

// MockInvariantMockRecorder is the mock recorder for MockInvariant.
type MockInvariantMockRecorder struct {
	mock *MockInvariant
}

// NewMockInvariant creates a new mock instance.
func NewMockInvariant(ctrl *gomock.Controller) *MockInvariant {
	mock := &MockInvariant{ctrl: ctrl}
	mock.recorder = &MockInvariantMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvariant) EXPECT() *MockInvariantMockRecorder {
	return m.recorder
}

// InputType mocks base method.
func (m *MockInvariant) InputType() core.RegisterType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(core.RegisterType)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockInvariantMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockInvariant)(nil).InputType))
}

// Invalidate mocks base method.
func (m *MockInvariant) Invalidate(arg0 core.TransitData) (*core.InvalOutcome, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", arg0)
	ret0, _ := ret[0].(*core.InvalOutcome)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockInvariantMockRecorder) Invalidate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockInvariant)(nil).Invalidate), arg0)
}

// SUUID mocks base method.
func (m *MockInvariant) SUUID() core.SUUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SUUID")
	ret0, _ := ret[0].(core.SUUID)
	return ret0
}

// SUUID indicates an expected call of SUUID.
func (mr *MockInvariantMockRecorder) SUUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SUUID", reflect.TypeOf((*MockInvariant)(nil).SUUID))
}

// SetSUUID mocks base method.
func (m *MockInvariant) SetSUUID(arg0 core.SUUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSUUID", arg0)
}

// SetSUUID indicates an expected call of SetSUUID.
func (mr *MockInvariantMockRecorder) SetSUUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSUUID", reflect.TypeOf((*MockInvariant)(nil).SetSUUID), arg0)
}

// ValidateInput mocks base method.
func (m *MockInvariant) ValidateInput(arg0 core.TransitData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateInput", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateInput indicates an expected call of ValidateInput.
func (mr *MockInvariantMockRecorder) ValidateInput(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateInput", reflect.TypeOf((*MockInvariant)(nil).ValidateInput), arg0)
}
