# Generation assurance test workflow
# (e.g. no uncovered diffs in go-mocks)
name: gen-test

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  ensure-mock-gen:
    name: Ensure mock generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: Mock diff check
        run: make go-gen-mocks && git diff --exit-code
