# Static security scan using Salus
# https://github.com/federacy/scan-action
name: salus-security-scan
on:

  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    name: Salus Security Scan Example
    steps:
    - uses: actions/checkout@v3
    - name: Salus Scan
      id: salus_scan
      uses: federacy/scan-action@0.1.4
      with:
          enforced_scanners: "none"
