# Validate OpenAPI spec on push and pull request

name: swagger-validate
on:

  push:
    branches: [ "master", "development" ]

  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g @apidevtools/swagger-cli
      - run: swagger-cli validate ./specs/openapi/swagger.yaml