name: Trufflehog

on:
  push:
    branches: [ "master", "development" ]
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  # Scan for secrets with trufflehog; surface verified only.
  # https://github.com/trufflesecurity/trufflehog
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@1cc41e2c757017b55e447c015485e166486376c1 #v3.63.7
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --only-verified

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
